# Generated by Django 2.2.12 on 2020-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangModel',
            fields=[
                ('nama', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('harga', models.IntegerField(blank=True, null=True)),
                ('harga_renceng', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
