# Generated by Django 2.2.12 on 2020-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangmodel',
            name='no_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barangmodel',
            name='nama',
            field=models.CharField(max_length=160),
        ),
    ]
