# Generated by Django 2.2.12 on 2020-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cek', '0002_auto_20200911_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmodel',
            name='no_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
