# Generated by Django 2.2.12 on 2020-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cek', '0003_auto_20200911_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmodel',
            name='no_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
